linters:
  enable:
    - goimports
    - nilerr
    - forcetypeassert
    - asciicheck
    - bodyclose
    - durationcheck
    - errorlint
    - noctx
    - misspell
    - exportloopref
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  misspell:
    ignore-words:
      # elf RELA
      - rela
      - equalisation
      - synchronisation
