version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gosec
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    - tagliatelle
    - unconvert
    - unparam
    - wastedassign
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G401
        - G501
        - G115
        - G406
        - G506
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      ignore-rules:
        - rela
        - equalisation
        - synchronisation
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - all
      excludes:
        # allow underscore
        - "ST1003"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - dev
      - doc
      # ignore warnings in code from crypto/tls and zmap/zcrypto
      - format/tls/tlsdecrypt
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - dev
      - doc
      - format/tls/tlsdecrypt
      - third_party$
      - builtin$
      - examples$
