#!/usr/bin/env expect
# TODO: move this script somehwere else
# TODO: run without NODECODEPROGRESS
# TODO: test interrupt?

log_user 1
set timeout 1

expect_after {
    timeout {exit 1}
}

spawn sh -c "NODECODEPROGRESS=1 fq -o color=false -i . pkg/interp/testdata/test.mp3 2>&1"

expect "mp3> "

send ".\n"
expect "footers"
expect "mp3> "

send ".frames | mp3_fr\t"
expect "mp3_frame"
send "\n"
expect "side_info"

# ctrl-d
send "\x04"

expect eof
