package all

import (
	//_ "fq/pkg/format/flv"

	_ "fq/pkg/format/ape"
	_ "fq/pkg/format/av1"
	_ "fq/pkg/format/bzip2"
	_ "fq/pkg/format/dns"
	_ "fq/pkg/format/elf"
	_ "fq/pkg/format/flac"
	_ "fq/pkg/format/gif"
	_ "fq/pkg/format/gzip"
	_ "fq/pkg/format/icc"
	_ "fq/pkg/format/id3"
	_ "fq/pkg/format/jpeg"
	_ "fq/pkg/format/matroska"
	_ "fq/pkg/format/mp3"
	_ "fq/pkg/format/mp4"
	_ "fq/pkg/format/mpeg"
	_ "fq/pkg/format/ogg"
	_ "fq/pkg/format/opus"
	_ "fq/pkg/format/png"
	_ "fq/pkg/format/protobuf"
	_ "fq/pkg/format/raw"
	_ "fq/pkg/format/tar"
	_ "fq/pkg/format/tiff"
	_ "fq/pkg/format/vorbis"
	_ "fq/pkg/format/vpx"
	_ "fq/pkg/format/wav"
	_ "fq/pkg/format/webp"
)
