package mbr

import (
	"github.com/wader/fq/pkg/scalar"
)

// Source: https://thestarman.pcministry.com/asm/mbr/PartTypes.htm
var partitionTypes scalar.UToDescription = scalar.UToDescription{
	0x00: "empty",
	0x01: "12-bit FAT",
	0x02: "XENIX root",
	0x03: "XENIX /usr (obsolete)",
	0x04: "16-bit FAT",
	0x05: "Extended Partition",
	0x06: "16-bit FAT, partition",
	0x07: "Installable file systems: HPFS or NTFS. Also, QNX and Advanced Unix.",
	0x08: "AIX bootable partition",
	0x09: "AIX data partition",
	0x0A: "Coherent swap partition, OPUS or OS/2 Boot Manager.",
	0x0B: "32-bit FAT",
	0x0C: "32-bit FAT, using INT 13 Extensions.",
	0x0E: "16-bit FAT >= 32 MB, using INT 13 Extensions.",
	0x0F: "Extended Partition, using INT 13 Extensions",
	0x10: "OPUS",
	0x11: "Hidden 12-bit FAT.",
	0x12: "Compaq diagnostics.",
	0x14: "Hidden 16-bit FAT",
	0x16: "Hidden 16-bit FAT, partition >= 32 MB",
	0x17: "Hidden IFS (HPFS, NTFS).",
	0x18: "AST Windows swap file",
	0x19: "Willowtech Photon coS",
	0x1B: "Hidden 32-bit FAT",
	0x1C: "Hidden 32-bit FAT, Ext INT 13",
	0x1E: "Hidden 16-bit FAT >32 MB, Ext. INT 13 (PowerQuest specific)",
	0x20: "Willowsoft Overture File System (OFS1)",
	0x21: "reserved (HP Volume Expansion, SpeedStor variant)",
	0x22: "Oxygen Extended",
	0x23: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x24: "NEC MS-DOS 3.x",
	0x26: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x31: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x33: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x34: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x36: "reserved (HP Volume Expansion, SpeedStor variant?)",
	0x38: "Theos",
	0x3C: "PowerQuest Files Partition Format",
	0x3D: "Hidden NetWare",
	0x40: "VENIX 80286",
	0x41: "Personal RISC Boot, PowerPC boot partition",
	0x42: "Secure File System, Windows 2000/XP (NT 5)",
	0x43: "Alternative Linux native file system (EXT2fs) PTS-DOS 6.70 & BootWizard: DR-DOS",
	0x45: "Priam, EUMEL/Elan. ",
	0x46: "EUMEL/Elan",
	0x47: "EUMEL/Elan",
	0x48: "EUMEL/Elan",
	0x4A: "ALFS/THIN lightweight filesystem for DOS",
	0x4D: "QNX",
	0x4E: "QNX",
	0x4F: "QNX, Oberon boot/data partition.",
	0x50: "Ontrack Disk Manager, read-only partition, FAT partition (Logical sector size varies)",
	0x51: "Ontrack Disk Manager, read/write partition, FAT partition (Logical sector size varies) Novell?",
	0x52: "CP/M, Microport System V/386.",
	0x53: "Ontrack Disk Manager, write-only",
	0x54: "Ontrack Disk Manager 6.0 (DDO)",
	0x55: "EZ-Drive 3.05",
	0x56: "Golden Bow VFeature",
	0x5C: "Priam EDISK",
	0x61: "Storage Dimensions SpeedStor",
	0x63: "GNU HURD, Mach, MtXinu BSD 4.2 on Mach, Unix Sys V/386, 386/ix.",
	0x64: "Novell NetWare 286, SpeedStore.",
	0x65: "Novell NetWare (3.11 and 4.1)",
	0x66: "Novell NetWare 386",
	0x67: "Novell NetWare",
	0x68: "Novell NetWare",
	0x69: "Novell NetWare 5+",
	0x70: "DiskSecure Multi-Boot",
	0x75: "IBM PC/IX",
	0x80: "Minix v1.1 - 1.4a, Old MINIX (Linux).",
	0x81: "Linux/Minix v1.4b+, Mitac Advanced Disk Manager.",
	0x82: "Linux Swap partition, Prime or Solaris (Unix).",
	0x83: "Linux native file systems (ext2/3/4, JFS, Reiser, xiafs, and others).",
	0x84: "OS/2 hiding type 04h partition",
	0x86: "NT Stripe Set, Volume Set?",
	0x87: "NT Stripe Set, Volume Set?, HPFS FT mirrored partition.",
	0x93: "Amoeba file system, Hidden Linux EXT2 partition (PowerQuest).",
	0x94: "Amoeba bad block table",
	0x99: "Mylex EISA SCSI",
	0x9F: "BSDI",
	0xA0: "Phoenix NoteBios Power Management 'Save to Disk', IBM hibernation.",
	0xA1: "HP Volume Expansion (SpeedStor variant)",
	0xA3: "HP Volume Expansion (SpeedStor variant)",
	0xA4: "HP Volume Expansion (SpeedStor variant)",
	0xA5: "FreeBSD/386",
	0xA6: "OpenBSD",
	0xA7: "NextStep Partition",
	0xA9: "NetBSD",
	0xAA: "Olivetti DOS with FAT12",
	0xB0: "Bootmanager BootStar by Star-Tools GmbH",
	0xB1: "HP Volume Expansion (SpeedStor variant)",
	0xB3: "HP Volume Expansion (SpeedStor variant)",
	0xB4: "HP Volume Expansion (SpeedStor variant)",
	0xB6: "HP Volume Expansion (SpeedStor variant)",
	0xB7: "BSDI file system or secondarily swap",
	0xB8: "BSDI swap partition or secondarily file system",
	0xBB: "PTS BootWizard (hidden) 4.0",
	0xBC: "May be an Acronis 'Backup' or 'Secure Zone' partition, when labeled 'ACRONIS SZ' (FAT32, LBA mapped, primary).",
	0xBE: "Solaris boot partition",
	0xC0: "Novell DOS/OpenDOS/DR-OpenDOS/DR-DOS secured partition, or CTOS (reported by a client).",
	0xC1: "DR-DOS 6.0 LOGIN.EXE-secured 12-bit FAT partition",
	0xC2: "Reserved for DR-DOS 7+",
	0xC3: "Reserved for DR-DOS 7+",
	0xC4: "DR-DOS 6.0 LOGIN.EXE-secured 16-bit FAT partition",
	0xC6: "DR-DOS 6.0 LOGIN.EXE-secured Huge partition, or: Corrupted FAT16 volume/stripe (V/S) set (Windows NT).",
	0xC7: "Syrinx, Cyrnix, HPFS FT disabled mirrored partition, or: Corrupted NTFS volume/stripe set.",
	0xC8: "Reserved for DR-DOS 7+",
	0xC9: "Reserved for DR-DOS 7+",
	0xCA: "Reserved for DR-DOS 7+",
	0xCB: "Reserved for DR-DOS secured FAT32",
	0xCC: "Reserved for DR-DOS secured FAT32X (LBA)",
	0xCD: "Reserved for DR-DOS 7+",
	0xCE: "Reserved for DR-DOS secured FAT16X (LBA)",
	0xCF: "Reserved for DR-DOS secured Extended partition (LBA)",
	0xD0: "Multiuser DOS secured (FAT12???)",
	0xD1: "Old Multiuser DOS secured FAT12",
	0xD4: "Old Multiuser DOS secured FAT16 (<= 32M)",
	0xD5: "Old Multiuser DOS secured extended partition",
	0xD6: "Old Multiuser DOS secured FAT16 (BIGDOS > 32 Mb)",
	0xD8: "CP/M 86",
	0xDB: "CP/M, Concurrent CP/M, Concurrent DOS, or CTOS (Convergent Technologies OS).",
	0xDE: "Dell partition. Normally it contains a FAT16 file system of about 32 MB.",
	0xDF: "BootIt EMBRM",
	0xE1: "SpeedStor 12-bit FAT Extended partition, DOS access (Linux).",
	0xE2: "DOS read-only (Florian Painke's XFDISK 1.0.4)",
	0xE3: "SpeedStor (Norton, Linux says DOS R/O)",
	0xE4: "SpeedStor 16-bit FAT Extended partition",
	0xE5: "Tandy DOS with logical sectored FAT",
	0xE6: "Storage Dimensions SpeedStor",
	0xEB: "BeOS file system",
	0xED: "Reserved for Matthias Paul's Spryt*x",
	0xEE: "GPT Protective MBR followed by a GPT/EFI Header. Used to define a fake partition covering the entire disk.",
	0xEF: "EFI/UEFI System Partition (or ESP)",
	0xF1: "SpeedStor Dimensions (Norton,Landis)",
	0xF2: "DOS 3.3+ second partition, Unisys DOS with logical sectored FAT.",
	0xF3: "Storage Dimensions SpeedStor",
	0xF4: "SpeedStor Storage Dimensions (Norton,Landis)",
	0xF5: "Prologue",
	0xF6: "Storage Dimensions SpeedStor",
	0xFD: "Reserved for FreeDOS (http://www.freedos.org)",
	0xFE: "LANstep, IBM PS/2 IML (Initial Microcode Load) partition, or...",
	0xFF: "Xenix bad-block table",
}
