name: "Automatic version updates"
on:
  schedule:
    # minute hour dom month dow (UTC)
    - cron: "0 16 * * *"
  # enable manual trigger of version updates
  workflow_dispatch:
jobs:
  version_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # to allow push changes of workflow config
          token: ${{ secrets.BUMP_TOKEN }}
      - uses: wader/bump/action/go@master
        env:
          GITHUB_TOKEN: ${{ secrets.BUMP_TOKEN }}
