package mp4

// based on https://github.com/HexFiend/HexFiend/blob/master/templates/Media/MOV.tcl

var boxDescriptions = map[string]string{
	"ainf":       "Asset information to identify, license and play",
	"assp":       "Alternative startup sequence properties",
	"avcn":       "AVC NAL Unit Storage Box",
	"bidx":       "Box Index",
	"bloc":       "Base location and purchase location for license acquisition",
	"bpcc":       "Bits per component",
	"buff":       "Buffering information",
	"bxml":       "Binary XML container",
	"ccid":       "OMA DRM Content ID",
	"cdef":       "Type and ordering of the components within the codestream",
	"cinf":       "Complete track information",
	"cmap":       "Mapping between a palette and codestream components",
	"co64":       "64-bit chunk offset",
	"coin":       "Content Information Box",
	"colr":       "Specifies the colourspace of the image",
	"crhd":       "Reserved for ClockReferenceStream header",
	"csgp":       "Compact sample to group",
	"cslg":       "Composition to decode timeline mapping",
	"ctts":       "Composition time to sample",
	"cvru":       "OMA DRM Cover URI",
	"dihd":       "Data Integrity Hash",
	"dinf":       "Data information box, container",
	"dint":       "Data Integrity",
	"dref":       "Data reference box, declares source(s) of media data in track",
	"dsgd":       "DVB Sample Group Description Box",
	"dstg":       "DVB Sample to Group Box",
	"edts":       "Edit list container",
	"elst":       "An edit list",
	"emsg":       "Event message",
	"evti":       "Event information",
	"etyp":       "Extended type and type combination",
	"fdel":       "File delivery information (item info extension)",
	"feci":       "FEC Informatiom",
	"fecr":       "FEC Reservoir",
	"fidx":       "Box File Index",
	"fiin":       "FD Item Information",
	"fire":       "File Reservoir",
	"fpar":       "File Partition",
	"free":       "Free space",
	"frma":       "Original format box",
	"frpa":       "Front Part",
	"ftyp":       "File type and compatibility",
	"gitn":       "Group ID to name",
	"grpi":       "OMA DRM Group ID",
	"grpl":       "Groups List box",
	"hdlr":       "Handler, declares the media (handler) type",
	"hmhd":       "Hint media header, overall information (hint track only)",
	"hpix":       "Hipix Rich Picture (user-data or meta-data)",
	"icnu":       "OMA DRM Icon URI",
	"ID32":       "ID3 version 2 container",
	"idat":       "Item data",
	"ihdr":       "Image Header",
	"iinf":       "Item information",
	"iloc":       "Item location",
	"imda":       "Identified media data",
	"imif":       "IPMP Information box",
	"infe":       "Item information entry",
	"infu":       "OMA DRM Info URL",
	"iods":       "Object Descriptor container box",
	"ipco":       "ItemPropertyContainerBox",
	"iphd":       "Reserved for IPMP Stream header",
	"ipma":       "ItemPropertyAssociation",
	"ipmc":       "IPMP Control Box",
	"ipro":       "Item protection",
	"iprp":       "Item Properties Box",
	"iref":       "Item reference",
	"jP\x20\x20": "JPEG 2000 Signature",
	"jp2c":       "JPEG 2000 contiguous codestream",
	"jp2h":       "Header",
	"jp2i":       "Intellectual property information",
	"leva":       "Leval assignment",
	"loop":       "Looping behavior",
	"lrcu":       "OMA DRM Lyrics URI",
	"m7hd":       "Reserved for MPEG7Stream header",
	"md5i":       "MD5IntegrityBox",
	"mdat":       "Media data container",
	"mdhd":       "Media header, overall information about the media",
	"mdia":       "Container for the media information in a track",
	"mdri":       "Mutable DRM information",
	"meco":       "Additional metadata container",
	"mehd":       "Movie extends header box",
	"mere":       "Metabox relation",
	"meta":       "Metadata container",
	"mfhd":       "Movie fragment header",
	"mfra":       "Movie fragment random access",
	"mfro":       "Movie fragment random access offset",
	"minf":       "Media information container",
	"mjhd":       "Reserved for MPEG-J Stream header",
	"moof":       "Movie fragment",
	"moov":       "Container for all the meta-data",
	"mstv":       "MVC sub track view box",
	"mvcg":       "Multiview group",
	"mvci":       "Multiview Information",
	"mvdr":       "MVDDepthResolutionBox",
	"mvex":       "Movie extends box",
	"mvhd":       "Movie header, overall declarations",
	"mvra":       "Multiview Relation Attribute",
	"nmhd":       "Null media header, overall information (some tracks only)",
	"ochd":       "Reserved for ObjectContentInfoStream header",
	"odaf":       "OMA DRM Access Unit Format",
	"odda":       "OMA DRM Content Object",
	"odhd":       "Reserved for ObjectDescriptorStream header",
	"odhe":       "OMA DRM Discrete Media Headers",
	"odrb":       "OMA DRM Rights Object",
	"odrm":       "OMA DRM Container",
	"odtt":       "OMA DRM Transaction Tracking",
	"ohdr":       "OMA DRM Common headers",
	"padb":       "Sample padding bits",
	"paen":       "Partition Entry",
	"pclr":       "Palette which maps a single component in index space to a multiple- component image",
	"pdat":       "Partial Data",
	"pdin":       "Progressive download information",
	"pfhd":       "Partial File Header",
	"pfil":       "Partial File",
	"pitm":       "Primary item reference",
	"ploc":       "Partial Segment Location",
	"prft":       "Producer reference time",
	"pseg":       "Partial Segment",
	"pshd":       "Partial Segment Header",
	"pssh":       "Protection system specific header",
	"ptle":       "Partial Top Level Entry",
	"res\x20":    "Grid resolution",
	"resc":       "Grid resolution at which the image was captured",
	"resd":       "Default grid resolution at which the image should be displayed",
	"rinf":       "Restricted scheme information box",
	"saio":       "Sample auxiliary information offsets",
	"saiz":       "Sample auxiliary information sizes",
	"sbgp":       "Sample to Group box",
	"schi":       "Scheme information box",
	"schm":       "Scheme type box",
	"sdep":       "Sample dependency",
	"sdhd":       "Reserved for SceneDescriptionStream header",
	"sdtp":       "Independent and Disposable Samples Box",
	"sdvp":       "SD Profile Box",
	"segr":       "File delivery session group",
	"seii":       "SEI information box",
	"senc":       "Sample specific encryption data",
	"sgpd":       "Sample group definition box",
	"sidx":       "Segment Index Box",
	"sinf":       "Protection scheme information box",
	"skip":       "Free space",
	"smhd":       "Sound media header, overall information (sound track only)",
	"srmb":       "System Renewability Message",
	"srmc":       "System Renewability Message container",
	"srpp":       "STRP Process",
	"ssix":       "Sub-sample index",
	"sstl":       "SVC sub track layer box",
	"stbl":       "Sample table box, container for the time/space map",
	"stco":       "Chunk offset, partial data-offset information",
	"stdp":       "Sample degradation priority",
	"sthd":       "Subtitle Media Header Box",
	"stmg":       "MVC sub track multiview group box",
	"strd":       "Sub-track definition",
	"stri":       "Sub-track information",
	"stsc":       "Sample-to-chunk, partial data-offset information",
	"stsd":       "Sample descriptions (codec types, initialization etc.)",
	"stsg":       "Sub-track sample grouping",
	"stsh":       "Shadow sync sample table",
	"stss":       "Sync sample table (random access points)",
	"stsz":       "Sample sizes (framing)",
	"stti":       "Sub track tier box",
	"stts":       "Sample time-to-sample",
	"styp":       "Segment Type Box",
	"stz2":       "Compact sample sizes (framing)",
	"subs":       "Sub-sample information",
	"surl":       "Source URL",
	"swtc":       "Multiview Group Relation",
	"tenc":       "Track Encryption",
	"tfad":       "Track fragment adjustment box",
	"tfdt":       "Track fragment decode time",
	"tfhd":       "Track fragment header",
	"tfma":       "Track fragment media adjustment box",
	"tfra":       "Track fragment radom access",
	"tibr":       "Tier Bit rate",
	"tiri":       "Tier Information",
	"tkhd":       "Track header, overall information about the track",
	"traf":       "Track fragment",
	"trak":       "Container for an individual track or stream",
	"tref":       "Track reference container",
	"trep":       "Track extension properties",
	"trex":       "Track extends defaults",
	"trgr":       "Track grouping information",
	"trik":       "Facilitates random access and trick play modes",
	"trun":       "Track fragment run",
	"tstb":       "TileSubTrackGroupBox",
	"ttyp":       "Track type and compatibility",
	"tyco":       "Type and-combination",
	"udta":       "User-data",
	"uinf":       "A tool by which a vendor may provide access to additional information associated with a UUID",
	"UITS":       "Unique Identifier Technology Solution",
	"ulst":       "A list of UUID’s",
	"url\x20":    "A URL",
	"uuid":       "User-extension box",
	"vmhd":       "Video media header, overall information (video track only)",
	"vwdi":       "Multiview Scene Information",
	"xml\x20":    "XML container",
	"j2kH":       "JPEG 2000 header item property",
	"albm":       "Album title and track number for media",
	"alou":       "Album loudness base",
	"angl":       "Name of the camera angle through which the clip was shot",
	"auth":       "Author of the media",
	"clfn":       "Name of the clip file",
	"clid":       "Identifier of the clip",
	"clsf":       "Classification of the media",
	"cmid":       "Identifier of the camera",
	"cmnm":       "Name that identifies the camera",
	"coll":       "Name of the collection from which the media comes",
	"cprt":       "Copyright etc.",
	"date":       "Date and time, formatted according to ISO 8601, when the content was created. For clips captured by recording devices, this is typically the date and time when the clip’s recording started.",
	"dscp":       "Media description",
	"gnre":       "Media genre",
	"hinf":       "Hint information",
	"hnti":       "Hint information",
	"kind":       "Track kind",
	"kywd":       "Media keywords",
	"loci":       "Media location information",
	"ludt":       "Track loudness container",
	"manu":       "Manufacturer name of the camera",
	"modl":       "Model name of the camera",
	"orie":       "Orientation information",
	"perf":       "Media performer name",
	"reel":       "Name of the tape reel",
	"rtng":       "Media rating",
	"scen":       "Name of the scene for which the clip was shot",
	"shot":       "Name that identifies the shot",
	"slno":       "Serial number of the camera",
	"strk":       "Sub track information",
	"thmb":       "Thumbnail image of the media",
	"titl":       "Media title",
	"tlou":       "Track loudness base",
	"tsel":       "Track selection",
	"urat":       "User 'star' rating of the media",
	"yrrc":       "Year when media was recorded",
	"clip":       "Visual clipping region container",
	"crgn":       "Visual clipping region definition",
	"ctab":       "Track color-table",
	"dcfD":       "Marlin DCF Duration, user-data atom type",
	"elng":       "Extended Language Tag",
	"imap":       "Track input map definition",
	"kmat":       "Compressed visual track matte",
	"load":       "Track pre-load definitions",
	"matt":       "Visual track matte for compositing",
	"pnot":       "Preview container",
	"wide":       "Expansion space reservation",
	"fiel":       "Video field order",

	"\x00\x00\x00\x00": "Terminator Atom",
}
